import { createContext, useContext, useState, ReactNode, useCallback } from "react";

export type Language = "fr" | "en" | "it" | "pt";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    "nav.home": "Accueil",
    "nav.cedf": "CEDF",
    "nav.about": "À Propos",
    "nav.missions": "Nos Missions",
    "nav.activities": "Activités",
    "nav.faq": "FAQ",
    "nav.news": "Actualités",
    "nav.teachings": "Enseignements",
    "nav.documents": "Documents & Archives",
    "nav.bible": "Bible en Ligne",
    "nav.radio": "Émissions & Radio",
    "nav.spiritual": "Vie Spirituelle",
    "nav.prayers": "Prières",
    "nav.saint": "Saint du Jour",
    "nav.calendar": "Calendrier Liturgique",
    "nav.shop": "Boutique",
    "nav.contact": "Contact",
    "nav.listen": "Écouter",
    "nav.listen_radio": "Écouter la Radio en direct",
    "hero.badge": "COMMISSION EPISCOPALE POUR LA DOCTRINE DE LA FOI – CI",
    "hero.title1": "Promouvoir et Défendre",
    "hero.title2": "le Dépôt de la Foi",
    "hero.quote": "« Je suis le Chemin, la Vérité et la Vie. »",
    "hero.quote_ref": "— Jean 14:6",
    "hero.teachings_btn": "Enseignements",
    "hero.teachings_full": "Découvrir les enseignements",
    "hero.radio_playing": "En cours...",
    "hero.radio_btn": "🎧 Radio",
    "hero.scroll": "Défiler",
    "shop.title": "Boutique",
    "shop.subtitle": "Objets de piété pour une vie spirituelle",
    "shop.search": "Rechercher un article...",
    "shop.all": "Tous",
    "shop.cart": "Panier",
    "shop.empty_cart": "Votre panier est vide",
    "shop.total": "Total",
    "shop.out_of_stock": "Rupture de stock",
    "shop.contact_order": "Pour toute commande, contactez-nous par téléphone ou par email.",
    "shop.payment_methods": "Moyens de paiement acceptés",
    "sub.our_productions": "Nos Productions",
    "sub.subscribe_to": "Abonnez-vous à la",
    "sub.revue_credo": "Revue Credo",
    "sub.description": "La foi expliquée, la foi vécue — Recevez chaque parution de notre revue spécialisée directement chez vous.",
    "sub.digital": "Numérique",
    "sub.digital_name": "Credo Digital",
    "sub.digital_desc": "Accès PDF à toutes les parutions",
    "sub.paper": "Papier",
    "sub.paper_name": "Credo Papier",
    "sub.paper_desc": "Livraison à domicile en Côte d'Ivoire",
    "sub.premium": "Premium",
    "sub.premium_name": "Credo Intégral",
    "sub.premium_desc": "Papier + Numérique + Bonus",
    "sub.popular": "Populaire",
    "sub.per_year": "/ an",
    "sub.subscribe": "S'abonner",
    "sub.subscribe_now": "S'abonner maintenant",
    "sub.feature_digital_1": "4 parutions par an en PDF",
    "sub.feature_digital_2": "Archives numériques incluses",
    "sub.feature_digital_3": "Accès immédiat après paiement",
    "sub.feature_paper_1": "4 parutions papier livrées",
    "sub.feature_paper_2": "Accès numérique offert",
    "sub.feature_paper_3": "Livraison gratuite en CI",
    "sub.feature_paper_4": "Numéros spéciaux inclus",
    "sub.feature_premium_1": "Tout Credo Papier inclus",
    "sub.feature_premium_2": "Documents exclusifs CEDF",
    "sub.feature_premium_3": "Invitations aux événements",
    "sub.feature_premium_4": "Mention dans la revue",
    "news.headline": "À la Une",
    "news.major_events": "Événements",
    "news.major": "Majeurs",
    "news.events_desc": "Les grands rendez-vous de l'Église catholique en Côte d'Ivoire et en Afrique",
    "news.learn_more": "En savoir plus",
    "news.latest": "Dernières",
    "news.latest_news": "Actualités",
    "news.latest_desc": "Suivez les dernières nouvelles de l'Église catholique en Côte d'Ivoire",
    "news.read_more": "Lire la suite",
    "news.inspiring": "Paroles Inspirantes",
    "news.comments": "Commentaires &",
    "news.citations": "Citations",
    "news.citations_desc": "Les paroles des évêques et des prêtres pour nourrir notre foi",
  },
  en: {
    "nav.home": "Home",
    "nav.cedf": "CEDF",
    "nav.about": "About Us",
    "nav.missions": "Our Missions",
    "nav.activities": "Activities",
    "nav.faq": "FAQ",
    "nav.news": "News",
    "nav.teachings": "Teachings",
    "nav.documents": "Documents & Archives",
    "nav.bible": "Online Bible",
    "nav.radio": "Shows & Radio",
    "nav.spiritual": "Spiritual Life",
    "nav.prayers": "Prayers",
    "nav.saint": "Saint of the Day",
    "nav.calendar": "Liturgical Calendar",
    "nav.shop": "Shop",
    "nav.contact": "Contact",
    "nav.listen": "Listen",
    "nav.listen_radio": "Listen to Live Radio",
    "hero.badge": "EPISCOPAL COMMISSION FOR THE DOCTRINE OF THE FAITH – CI",
    "hero.title1": "Promote and Protect",
    "hero.title2": "the Deposit of Faith",
    "hero.quote": '"I am the Way, the Truth and the Life."',
    "hero.quote_ref": "— John 14:6",
    "hero.teachings_btn": "Teachings",
    "hero.teachings_full": "Discover the teachings",
    "hero.radio_playing": "Playing...",
    "hero.radio_btn": "🎧 Radio",
    "hero.scroll": "Scroll",
    "shop.title": "Shop",
    "shop.subtitle": "Objects of piety for a spiritual life",
    "shop.search": "Search for an item...",
    "shop.all": "All",
    "shop.cart": "Cart",
    "shop.empty_cart": "Your cart is empty",
    "shop.total": "Total",
    "shop.out_of_stock": "Out of stock",
    "shop.contact_order": "For any order, contact us by phone or email.",
    "shop.payment_methods": "Accepted payment methods",
    "sub.our_productions": "Our Publications",
    "sub.subscribe_to": "Subscribe to the",
    "sub.revue_credo": "Credo Review",
    "sub.description": "Faith explained, faith lived — Receive every issue of our specialized review directly at home.",
    "sub.digital": "Digital",
    "sub.digital_name": "Credo Digital",
    "sub.digital_desc": "PDF access to all issues",
    "sub.paper": "Paper",
    "sub.paper_name": "Credo Paper",
    "sub.paper_desc": "Home delivery in Côte d'Ivoire",
    "sub.premium": "Premium",
    "sub.premium_name": "Credo Full",
    "sub.premium_desc": "Paper + Digital + Bonus",
    "sub.popular": "Popular",
    "sub.per_year": "/ year",
    "sub.subscribe": "Subscribe",
    "sub.subscribe_now": "Subscribe now",
    "sub.feature_digital_1": "4 issues per year in PDF",
    "sub.feature_digital_2": "Digital archives included",
    "sub.feature_digital_3": "Immediate access after payment",
    "sub.feature_paper_1": "4 paper issues delivered",
    "sub.feature_paper_2": "Free digital access",
    "sub.feature_paper_3": "Free delivery in CI",
    "sub.feature_paper_4": "Special issues included",
    "sub.feature_premium_1": "All Credo Paper included",
    "sub.feature_premium_2": "Exclusive CEDF documents",
    "sub.feature_premium_3": "Event invitations",
    "sub.feature_premium_4": "Mention in the review",
    "news.headline": "Headlines",
    "news.major_events": "Major",
    "news.major": "Events",
    "news.events_desc": "Major events of the Catholic Church in Côte d'Ivoire and Africa",
    "news.learn_more": "Learn more",
    "news.latest": "Latest",
    "news.latest_news": "News",
    "news.latest_desc": "Follow the latest news from the Catholic Church in Côte d'Ivoire",
    "news.read_more": "Read more",
    "news.inspiring": "Inspiring Words",
    "news.comments": "Comments &",
    "news.citations": "Quotes",
    "news.citations_desc": "The words of bishops and priests to nourish our faith",
  },
  it: {
    "nav.home": "Home",
    "nav.cedf": "CEDF",
    "nav.about": "Chi Siamo",
    "nav.missions": "Le Nostre Missioni",
    "nav.activities": "Attività",
    "nav.faq": "FAQ",
    "nav.news": "Notizie",
    "nav.teachings": "Insegnamenti",
    "nav.documents": "Documenti & Archivi",
    "nav.bible": "Bibbia Online",
    "nav.radio": "Programmi & Radio",
    "nav.spiritual": "Vita Spirituale",
    "nav.prayers": "Preghiere",
    "nav.saint": "Santo del Giorno",
    "nav.calendar": "Calendario Liturgico",
    "nav.shop": "Negozio",
    "nav.contact": "Contatto",
    "nav.listen": "Ascolta",
    "nav.listen_radio": "Ascolta la Radio in diretta",
    "hero.badge": "COMMISSIONE EPISCOPALE PER LA DOTTRINA DELLA FEDE – CI",
    "hero.title1": "Promuovere e Proteggere",
    "hero.title2": "il Deposito della Fede",
    "hero.quote": '"Io sono la Via, la Verità e la Vita."',
    "hero.quote_ref": "— Giovanni 14:6",
    "hero.teachings_btn": "Insegnamenti",
    "hero.teachings_full": "Scopri gli insegnamenti",
    "hero.radio_playing": "In onda...",
    "hero.radio_btn": "🎧 Radio",
    "hero.scroll": "Scorri",
    "shop.title": "Negozio",
    "shop.subtitle": "Oggetti di pietà per una vita spirituale",
    "shop.search": "Cerca un articolo...",
    "shop.all": "Tutti",
    "shop.cart": "Carrello",
    "shop.empty_cart": "Il carrello è vuoto",
    "shop.total": "Totale",
    "shop.out_of_stock": "Esaurito",
    "shop.contact_order": "Per qualsiasi ordine, contattateci per telefono o email.",
    "shop.payment_methods": "Metodi di pagamento accettati",
    "sub.our_productions": "Le Nostre Pubblicazioni",
    "sub.subscribe_to": "Abbonati alla",
    "sub.revue_credo": "Rivista Credo",
    "sub.description": "La fede spiegata, la fede vissuta — Ricevi ogni numero della nostra rivista specializzata direttamente a casa.",
    "sub.digital": "Digitale",
    "sub.digital_name": "Credo Digitale",
    "sub.digital_desc": "Accesso PDF a tutti i numeri",
    "sub.paper": "Cartaceo",
    "sub.paper_name": "Credo Cartaceo",
    "sub.paper_desc": "Consegna a domicilio in Costa d'Avorio",
    "sub.premium": "Premium",
    "sub.premium_name": "Credo Integrale",
    "sub.premium_desc": "Cartaceo + Digitale + Bonus",
    "sub.popular": "Popolare",
    "sub.per_year": "/ anno",
    "sub.subscribe": "Abbonati",
    "sub.subscribe_now": "Abbonati ora",
    "sub.feature_digital_1": "4 numeri all'anno in PDF",
    "sub.feature_digital_2": "Archivi digitali inclusi",
    "sub.feature_digital_3": "Accesso immediato dopo il pagamento",
    "sub.feature_paper_1": "4 numeri cartacei consegnati",
    "sub.feature_paper_2": "Accesso digitale gratuito",
    "sub.feature_paper_3": "Consegna gratuita in CI",
    "sub.feature_paper_4": "Numeri speciali inclusi",
    "sub.feature_premium_1": "Tutto Credo Cartaceo incluso",
    "sub.feature_premium_2": "Documenti esclusivi CEDF",
    "sub.feature_premium_3": "Inviti agli eventi",
    "sub.feature_premium_4": "Menzione nella rivista",
    "news.headline": "In Primo Piano",
    "news.major_events": "Eventi",
    "news.major": "Principali",
    "news.events_desc": "I grandi appuntamenti della Chiesa cattolica in Costa d'Avorio e in Africa",
    "news.learn_more": "Scopri di più",
    "news.latest": "Ultime",
    "news.latest_news": "Notizie",
    "news.latest_desc": "Segui le ultime notizie della Chiesa cattolica in Costa d'Avorio",
    "news.read_more": "Leggi di più",
    "news.inspiring": "Parole Ispiratrici",
    "news.comments": "Commenti &",
    "news.citations": "Citazioni",
    "news.citations_desc": "Le parole dei vescovi e dei sacerdoti per nutrire la nostra fede",
  },
  pt: {
    "nav.home": "Início",
    "nav.cedf": "CEDF",
    "nav.about": "Sobre Nós",
    "nav.missions": "Nossas Missões",
    "nav.activities": "Atividades",
    "nav.faq": "FAQ",
    "nav.news": "Notícias",
    "nav.teachings": "Ensinamentos",
    "nav.documents": "Documentos & Arquivos",
    "nav.bible": "Bíblia Online",
    "nav.radio": "Programas & Rádio",
    "nav.spiritual": "Vida Espiritual",
    "nav.prayers": "Orações",
    "nav.saint": "Santo do Dia",
    "nav.calendar": "Calendário Litúrgico",
    "nav.shop": "Loja",
    "nav.contact": "Contato",
    "nav.listen": "Ouvir",
    "nav.listen_radio": "Ouvir Rádio ao vivo",
    "hero.badge": "COMISSÃO EPISCOPAL PARA A DOUTRINA DA FÉ – CI",
    "hero.title1": "Promover e Defender",
    "hero.title2": "o Depósito da Fé",
    "hero.quote": '"Eu sou o Caminho, a Verdade e a Vida."',
    "hero.quote_ref": "— João 14:6",
    "hero.teachings_btn": "Ensinamentos",
    "hero.teachings_full": "Descobrir os ensinamentos",
    "hero.radio_playing": "Tocando...",
    "hero.radio_btn": "🎧 Rádio",
    "hero.scroll": "Rolar",
    "shop.title": "Loja",
    "shop.subtitle": "Objetos de piedade para uma vida espiritual",
    "shop.search": "Procurar um artigo...",
    "shop.all": "Todos",
    "shop.cart": "Carrinho",
    "shop.empty_cart": "Seu carrinho está vazio",
    "shop.total": "Total",
    "shop.out_of_stock": "Esgotado",
    "shop.contact_order": "Para qualquer pedido, entre em contato por telefone ou e-mail.",
    "shop.payment_methods": "Métodos de pagamento aceitos",
    "sub.our_productions": "Nossas Publicações",
    "sub.subscribe_to": "Assine a",
    "sub.revue_credo": "Revista Credo",
    "sub.description": "A fé explicada, a fé vivida — Receba cada edição da nossa revista especializada diretamente em casa.",
    "sub.digital": "Digital",
    "sub.digital_name": "Credo Digital",
    "sub.digital_desc": "Acesso PDF a todas as edições",
    "sub.paper": "Papel",
    "sub.paper_name": "Credo Papel",
    "sub.paper_desc": "Entrega em domicílio na Costa do Marfim",
    "sub.premium": "Premium",
    "sub.premium_name": "Credo Integral",
    "sub.premium_desc": "Papel + Digital + Bônus",
    "sub.popular": "Popular",
    "sub.per_year": "/ ano",
    "sub.subscribe": "Assinar",
    "sub.subscribe_now": "Assinar agora",
    "sub.feature_digital_1": "4 edições por ano em PDF",
    "sub.feature_digital_2": "Arquivos digitais incluídos",
    "sub.feature_digital_3": "Acesso imediato após pagamento",
    "sub.feature_paper_1": "4 edições em papel entregues",
    "sub.feature_paper_2": "Acesso digital gratuito",
    "sub.feature_paper_3": "Entrega gratuita na CI",
    "sub.feature_paper_4": "Edições especiais incluídas",
    "sub.feature_premium_1": "Todo Credo Papel incluído",
    "sub.feature_premium_2": "Documentos exclusivos CEDF",
    "sub.feature_premium_3": "Convites para eventos",
    "sub.feature_premium_4": "Menção na revista",
    "news.headline": "Destaques",
    "news.major_events": "Eventos",
    "news.major": "Principais",
    "news.events_desc": "Os grandes encontros da Igreja Católica na Costa do Marfim e na África",
    "news.learn_more": "Saiba mais",
    "news.latest": "Últimas",
    "news.latest_news": "Notícias",
    "news.latest_desc": "Acompanhe as últimas notícias da Igreja Católica na Costa do Marfim",
    "news.read_more": "Leia mais",
    "news.inspiring": "Palavras Inspiradoras",
    "news.comments": "Comentários &",
    "news.citations": "Citações",
    "news.citations_desc": "As palavras dos bispos e sacerdotes para alimentar a nossa fé",
  },
};

const languageLabels: Record<Language, string> = {
  fr: "FR",
  en: "EN",
  it: "IT",
  pt: "PT",
};

const languageFlags: Record<Language, string> = {
  fr: "🇫🇷",
  en: "🇬🇧",
  it: "🇮🇹",
  pt: "🇵🇹",
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};

export { languageLabels, languageFlags };

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("cedf-language");
    return (saved as Language) || "fr";
  });

  const handleSetLanguage = useCallback((lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("cedf-language", lang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language]?.[key] || translations.fr[key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
